// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnY5ZepL9lmc3s6LGldvD0a7RvE-8bJQQ',
    appId: '1:97282975813:web:88e718428daee03deb5b2c',
    messagingSenderId: '97282975813',
    projectId: 'cameronharvest-dailyprice',
    authDomain: 'cameronharvest-dailyprice.firebaseapp.com',
    storageBucket: 'cameronharvest-dailyprice.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzOpkUNcgBQa8ggqhbBJLPyYP05iyiX_w',
    appId: '1:97282975813:android:f773fcc11aa660e0eb5b2c',
    messagingSenderId: '97282975813',
    projectId: 'cameronharvest-dailyprice',
    storageBucket: 'cameronharvest-dailyprice.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA0JZsWFZ-4diMslRO6-7_8C7_-JZQwKQ',
    appId: '1:97282975813:ios:944dc332b450a2b6eb5b2c',
    messagingSenderId: '97282975813',
    projectId: 'cameronharvest-dailyprice',
    storageBucket: 'cameronharvest-dailyprice.appspot.com',
    iosBundleId: 'com.greenlandpillar.price',
  );
}
